### ISSUE TITLE
Loading / Creating Event Issue

### ISSUE THREAD

**Issue by nathan492** [xybal/EventBookingProJqueryFix#1]
Thanks for making this for people. I was using the JS migrate helper plugin - i have swapped to use yours now. But even with yours on wordpress it wont let me create an event - just shows the loader ? Any ideas... and thanks again

**Comment by xybal** [comment]
Hey, when I made the fix I was just checking my existing events... I add a fix, tell me if it's ok.

**Comment by nathan492** [comment]
Yea that works - but adding doesn’t. What was the issue so I can try and fix it

**Comment by xybal** [comment]
Are you using a cache plugin ? If yes, try to purge it and your browser cache too it might be that. The issue was parsing a JSON object with an empty string (it was ok with old jquery but now it returns an error so I just added a condition to trigger the parsing of this JSON object only if the previous object isn't an empty string).

**Comment by xybal** [comment]
Reset the adminHelper.js back to the version here in the txt file and tell me if you can access to old / new forms. If yes, can you tell me what fields are in the ones triggering errors ?
[adminHelper.txt](https://github.com/xybal/EventBookingProJqueryFix/files/6167402/adminHelper.txt)
